var BenchConstants = {
  BENCHES_RECEIVED: "BENCHES_RECEIVED",
  CREATE_BENCH: "BENCH_CREATED",
  BORDER_PARAMS_UPDATED: "BORDER_PARAMS_UPDATED",
  SEATING_PARAMS_UPDATED: "SEATING_PARAMS_UPDATED"
};

module.exports = BenchConstants;
